spring:
  config:
    import: classpath:secret.yml
  profiles:
    active: dev
    include: secret
  data:
    web:
      pageable:
        one-indexed-parameters: true

# entity 이름을 테이블 이름과 동일하게 맞추기 // default = userName -> user_name {설정하면 = userName -> userName}
#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#custom:
#  site:

#    baseUrl: http://localhost