spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
  config:
    import: classpath:secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.location}:3306/bidbuy_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: studydev
    password: ${mysql.dev_password}

  jwt:
    secret: ${jwt.secret}
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            redirect-uri: ${location.dev}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
          naver:
            client-name: naver
            client-id: ${oauth.naver.client-id}
            client-secret: ${oauth.naver.client-secret}
            redirect-uri: ${location.dev}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: INFO
    org.duckdns.bidbuy: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE