spring:
  config:
    import: classpath:secret.yml
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bitwatchu_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: ${mysql.password}
logging:
  level:
    root: INFO
    org.duckdns.bitwatchu: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

# entity 이름을 테이블 이름과 동일하게 맞추기 // default = userName -> user_name {설정하면 = userName -> userName}
#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#custom:
#  site:
#    baseUrl: http://localhost